# Generated by Django 5.1.3 on 2024-12-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP адрес ПК')),
                ('ram_usage', models.FloatField(verbose_name='Нагрузка ОЗУ (%)')),
                ('cpu_usage', models.FloatField(verbose_name='Нагрузка процессора (%)')),
                ('log_time', models.DateTimeField(verbose_name='Время лога')),
                ('log_message', models.TextField(verbose_name='Сообщение лога')),
                ('temperature', models.FloatField(verbose_name='Температура (°C)')),
            ],
        ),
    ]
