# Generated by Django 5.1.3 on 2024-12-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_deviceinfo_systemlog_rename_log_time_log_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_load_proc', models.FloatField()),
                ('ram_usage_proc', models.FloatField()),
                ('network_sent_bytes', models.BigIntegerField()),
                ('network_recv_bytes', models.BigIntegerField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
