# Generated by Django 5.1.3 on 2024-12-05 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_metrics'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceinfo',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='systemlog',
            options={'managed': False},
        ),
    ]
