# Generated by Django 5.1.3 on 2024-12-05 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0004_alter_deviceinfo_options_alter_systemlog_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deviceinfo',
            table='device_info',
        ),
        migrations.AlterModelTable(
            name='systemlog',
            table='system_logs',
        ),
    ]
