# Generated by Django 5.1.3 on 2024-12-05 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0005_alter_deviceinfo_table_alter_systemlog_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
        migrations.DeleteModel(
            name='Metrics',
        ),
    ]
